### ISSUE TITLE
Handle different canvas size with percentage instead of coordinates

### ISSUE THREAD

**Issue by nathangobinet** [tylp/memo-draw-engine#15]
At the moment, we share canvas coordinates in the network. It works great on fixed size canvas. But what if players have different screen size ? It will not scale correctly....
So instead of full coordinates we should share percentage. I think a simple implementation can be found here :  https://github.com/socketio/socket.io/blob/master/examples/whiteboard/public/main.js

It's as simple as :

```js
socket.emit('drawing', {
      x0: x0 / w,
      y0: y0 / h,
      x1: x1 / w,
      y1: y1 / h,
      color: color
});
```

**Comment by adrien-nf** [comment]
Shouldn't this be treated in the actual MemoDraw project, as this regards socket? As far as I'm concerned, I feel like we should forget about sockets in this project, and assume that we have no idea what the user of this package will do with it.

**Comment by nathangobinet** [comment]
Mmmmh, this issue is indeed about sharing shapes across network. But that's actually what the library is made for, and why we have all this serialization stuffs. Furthermore, it's just that example who give to the socket the responsability to do the "responsive job". In our case it will be a lot easier to implement this in the factory.
