### ISSUE TITLE
Opacity fill is applied on empty canvas instead of on current color

### ISSUE THREAD

**Issue by adrien-nf** [tylp/memo-draw-engine#35]
For example, try to fill canvas with plain red, then with 20% blue: this should give purple-ish pink. Instead, this gives white (canvas) with 20% blue opacity.

Because of that, you can't gradually add opacity to a section: if you try to spam click 20% blue opacity, it will only apply the same color, 20% blue opacity, from background (white), thus never changing the color.

**Comment by nathangobinet** [comment]
Alors la je suis pas sur de l'utilité de la feature...
Mais c'est marrant... Alors je l'ai fait 😄 
https://github.com/tylp/memo-draw-engine/pull/39
