### ISSUE TITLE
Allow for clear of shapes history

### ISSUE THREAD

**Issue by adrien-nf** [tylp/memo-draw-engine#64]

**Comment by nathangobinet** [comment]
In addition to the shapeManager reset function ?
UndoRedoManager already expose a reset function.

**Comment by adrien-nf** [comment]
Yep so, here's the deal: I'm working on a project where players take turn on drawing.
A player draws multiple drawings back to back. Whenever he's done with a drawing, his canvas is cleared. This is only visual though, as when he tries to CTRL+Z in his new drawing, the old shapes are still present in the history, and this will redraw the previous drawing.

**Comment by nathangobinet** [comment]
🤔 

> Whenever he's done with a drawing, his canvas is cleared

How do you clear the canvas ?

It's supposed to be done on server side by sanding a `ActionType.Reset` event to the engine.

> This is only visual though, as when he tries to CTRL+Z in his new drawing, the old shapes are still present in the history, and this will redraw the previous drawing.

I was not able to reproduce this issue

**Comment by adrien-nf** [comment]
> How do you clear the canvas ?

Not the right way apparently, I'll try your way and report here.

**Comment by adrien-nf** [comment]
Alright, I see how it goes! Thanks.
