### ISSUE TITLE
drawState should be a property of engine, not a singleton

### ISSUE THREAD

**Issue by adrien-nf** [tylp/memo-draw-engine#65]

**Comment by nathangobinet** [comment]
I dont't know why you hate singleton that much.
But it can sure be done.

**Comment by adrien-nf** [comment]
We've transformed Engine from a singleton to an instance for the purpose of having multiple canvas at the same time! Having a singleton drawState means we can't really make that happen. I love Singleton, but I feel like it's a double edged sword!
